(()=>{
'use strict';
const d=document,w=window,root=d.documentElement;root.classList.add('js');
const exp=d.querySelector('link[href^="site-experience.css"]');if(exp)exp.href='site-experience.css?v=9';
const polish=d.querySelector('link[href^="final-polish.css"]');if(polish)polish.href='final-polish.css?v=4';
const addCss=(href,key)=>{if(d.querySelector(`[data-${key}]`))return;const l=d.createElement('link');l.rel='stylesheet';l.href=href;l.dataset[key]='';d.head.appendChild(l)};
if(matchMedia('(min-width:981px)').matches){const fn=()=>addCss('desktop-polish.css?v=2','desktopPolish');'requestIdleCallback'in w?w.requestIdleCallback(fn,{timeout:700}):setTimeout(fn,0)}
/* Visible brand atmosphere, separate from navigation and content logic. */
if(!d.querySelector('.brand-atmosphere')){const atmosphere=d.createElement('div');atmosphere.className='brand-atmosphere';atmosphere.setAttribute('aria-hidden','true');atmosphere.innerHTML='<span class="silk"></span><span class="motif"></span>';d.body.prepend(atmosphere)}
const instagram='https://www.instagram.com/boxes_tasmaarah_collection';
const whatsapp='https://wa.me/27635409729?text='+encodeURIComponent("Hi Tasmaarah Collection, I'd like a quote.");
const maps='https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent('Reservoir Hills, Durban, KwaZulu-Natal, South Africa')+'&travelmode=driving&dir_action=navigate';
const external=(href,cls,label,text)=>{const a=d.createElement('a');a.href=href;a.target='_blank';a.rel='noopener noreferrer';a.className=cls||'';a.setAttribute('aria-label',label||text||'Open link');if(text)a.textContent=text;return a};
const svg={instagram:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.4" cy="6.6" r="1" fill="currentColor" stroke="none"/></svg>',whatsapp:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20 11.5a8 8 0 0 1-11.8 7L4 20l1.5-4.1A8 8 0 1 1 20 11.5Z"/></svg>'};
const icon=(kind,href,label)=>{const a=external(href,`social-icon social-icon-${kind}`,label);a.innerHTML=svg[kind];return a};
const socials=()=>{const x=d.createElement('div');x.className='social-icons';x.append(icon('instagram',instagram,'Instagram'),icon('whatsapp',whatsapp,'WhatsApp'));return x};
const utility=d.querySelector('.utility-actions');if(utility&&!utility.querySelector('.instagram-link'))utility.append(external(instagram,'instagram-link','Instagram','Instagram'));
const panel=d.querySelector('.mobile-panel');if(panel&&!panel.querySelector('.mobile-instagram')){const a=external(instagram,'mobile-instagram','Instagram','Instagram ↗'),q=panel.querySelector('.mobile-quote');q?panel.insertBefore(a,q):panel.append(a)}
const footerContact=d.querySelector('.footer>div:nth-of-type(3)');if(footerContact&&!footerContact.querySelector('.footer-instagram')){footerContact.append(external(instagram,'footer-instagram','Instagram','Instagram @boxes_tasmaarah_collection'),socials())}
const socialCopy=d.querySelector('.social-showcase-copy');if(socialCopy&&!socialCopy.querySelector('.social-icons'))socialCopy.append(socials());
const footer=d.querySelector('.footer');if(footer&&!footer.querySelector('a[href="privacy.html"]')){const a=d.createElement('a');a.href='privacy.html';a.className='footer-privacy';a.textContent='Privacy & cookies';footer.querySelector('.credit')?.insertAdjacentElement('beforebegin',a)}
d.querySelectorAll('span,p,address,div').forEach(el=>{if(el.children.length)return;const t=(el.textContent||'').trim();if(!/^(Reservoir Hills(?:,\s*Durban)?|Based in Reservoir Hills(?:,\s*Durban)?)$/i.test(t))return;el.replaceWith(external(maps,'map-directions-link','Get directions to Reservoir Hills, Durban',t))});
try{if(localStorage.getItem('tasmaarahPrivacyNotice')!=='dismissed'&&!location.pathname.endsWith('privacy.html')){const n=d.createElement('aside');n.className='cookie-notice';n.innerHTML='<p><strong>Privacy & cookies</strong>This site does not currently use advertising or analytics cookies. <a href="privacy.html">Learn more</a>.</p><button type="button">Got it</button>';n.querySelector('button').onclick=()=>{localStorage.setItem('tasmaarahPrivacyNotice','dismissed');n.remove()};d.body.append(n)}}catch{}
const reduced=matchMedia('(prefers-reduced-motion: reduce)');d.body.dataset.motion=reduced.matches?'off':'on';d.querySelectorAll('.motion-toggle').forEach(x=>x.remove());
const menu=d.querySelector('.mobile-menu');if(menu){const summary=menu.querySelector('summary'),nav=menu.querySelector('.mobile-panel'),header=d.querySelector('.site-header');if(nav&&!nav.id)nav.id='mobile-navigation-panel';summary?.setAttribute('aria-controls',nav?.id||'mobile-navigation-panel');const pos=()=>root.style.setProperty('--mobile-menu-top',`${Math.max(0,Math.round(header?.getBoundingClientRect().bottom||82))}px`);const sync=()=>{const open=menu.open;summary?.setAttribute('aria-expanded',String(open));summary?.setAttribute('aria-label',open?'Close navigation':'Open navigation');d.body.classList.toggle('menu-open',open);d.body.style.overflow=open?'hidden':'';if(open)pos()};menu.addEventListener('toggle',sync);nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.open=false;sync()}));d.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu.open){menu.open=false;sync();summary?.focus()}});w.addEventListener('resize',()=>{if(menu.open)pos()},{passive:true});sync()}
let navRaf=0;const syncScrollNav=()=>{navRaf=0;d.body.classList.toggle('nav-scrolled',w.innerWidth<=980&&w.scrollY>96)};const queueScrollNav=()=>{if(!navRaf)navRaf=w.requestAnimationFrame(syncScrollNav)};w.addEventListener('scroll',queueScrollNav,{passive:true});w.addEventListener('resize',queueScrollNav,{passive:true});syncScrollNav();
w.addEventListener('pageshow',()=>{if(menu)menu.open=false;d.body.classList.remove('menu-open','lightbox-open');d.body.style.overflow='';syncScrollNav()});
const current=(location.pathname.split('/').pop()||'index.html').toLowerCase();d.querySelectorAll('.desktop-nav a,.mobile-panel a').forEach(a=>{if((a.getAttribute('href')||'').split('#')[0].toLowerCase()===current)a.setAttribute('aria-current','page')});
const cards=[...d.querySelectorAll('.catalog-card')],search=d.querySelector('[data-catalog-search]'),empty=d.querySelector('.empty-state');if(cards.length&&search){const filter=()=>{const q=search.value.trim().toLowerCase();let n=0;cards.forEach(c=>{const hit=!q||c.textContent.toLowerCase().includes(q);c.hidden=!hit;if(hit)n++});empty?.classList.toggle('show',!n)};search.addEventListener('input',filter);filter()}
const form=d.querySelector('#quote-form');if(form)form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const fd=new FormData(form),lines=["Hi Tasmaarah Collection, I'd like a quote.",''];for(const [k,v] of fd.entries())if(String(v).trim())lines.push(`${k}: ${v}`);location.href=`https://wa.me/27635409729?text=${encodeURIComponent(lines.join('\n'))}`});
const imgs=[...d.querySelectorAll('.masonry-gallery img')];if(imgs.length){const lb=d.createElement('div');lb.className='lightbox';lb.innerHTML='<button class="lightbox-close" type="button">×</button><figure><img alt=""><figcaption></figcaption></figure>';d.body.append(lb);const image=lb.querySelector('img'),cap=lb.querySelector('figcaption');const close=()=>{lb.classList.remove('open');d.body.style.overflow=''};imgs.forEach(im=>im.onclick=()=>{image.src=im.currentSrc||im.src;image.alt=im.alt;cap.textContent=im.alt;lb.classList.add('open');d.body.style.overflow='hidden'});lb.querySelector('button').onclick=close;lb.onclick=e=>{if(e.target===lb)close()}}
const fxSelectors=['main>section','.page-heading','.page-hero','.section-head','.campaign-spread-copy','.editorial-copy','.contact-intro-copy','.contact-form-heading','.gallery-grid figure','.masonry-gallery figure','.campaign-spread-grid figure','.catalog-card','.occasion-card','.social-visuals a','.fact-panel','.faq-list details'];
const fx=[...new Set(fxSelectors.flatMap(s=>[...d.querySelectorAll(s)]))];fx.forEach(el=>{el.classList.add('fx-item');if(el.matches('figure,.catalog-card,.occasion-card,.social-visuals a,.page-hero>img'))el.classList.add('fx-media');else el.classList.add('fx-text')});
if(!reduced.matches&&'IntersectionObserver'in w){fx.forEach(el=>{const r=el.getBoundingClientRect();if(r.top>innerHeight*.82)el.classList.add('fx-pending');else el.classList.add('fx-visible')});const fxio=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.remove('fx-pending');e.target.classList.add('fx-visible');fxio.unobserve(e.target)}}),{threshold:.12,rootMargin:'0px 0px -8% 0px'});fx.filter(el=>el.classList.contains('fx-pending')).forEach(el=>fxio.observe(el))}else fx.forEach(el=>el.classList.add('fx-visible'));
const reveals=[...d.querySelectorAll('[data-reveal]')];if('IntersectionObserver'in w&&!reduced.matches){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('reveal-enter');io.unobserve(e.target)}}),{threshold:.04,rootMargin:'12% 0px'});reveals.forEach(x=>io.observe(x))}else reveals.forEach(x=>x.classList.add('reveal-enter'));
d.querySelectorAll('main img').forEach(img=>{if(!img.classList.contains('hero-art')){img.decoding='async';if(!img.hasAttribute('loading'))img.loading='lazy'}});d.body.classList.add('site-ready');
})();