(()=>{
'use strict';
const root=document.documentElement;root.classList.add('js');
/* Desktop/tablet polish is additive and intentionally isolated from mobile stability rules. */
if(!document.querySelector('link[data-desktop-polish]')){const l=document.createElement('link');l.rel='stylesheet';l.href='desktop-polish.css?v=2';l.dataset.desktopPolish='';document.head.appendChild(l)}
const focusableSelector='a[href],button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])';
const trapTab=(e,c)=>{if(e.key!=='Tab'||!c)return;const f=[...c.querySelectorAll(focusableSelector)].filter(x=>x.offsetParent!==null);if(!f.length)return;const a=f[0],b=f[f.length-1];if(e.shiftKey&&document.activeElement===a){e.preventDefault();b.focus()}else if(!e.shiftKey&&document.activeElement===b){e.preventDefault();a.focus()}};
const instagramUrl='https://www.instagram.com/boxes_tasmaarah_collection';
const makeInstagram=(className,label)=>{const a=document.createElement('a');a.href=instagramUrl;a.target='_blank';a.rel='noopener noreferrer';a.className=className;a.textContent=label;a.setAttribute('aria-label','Tasmaarah Collection on Instagram');return a};
const utilityActions=document.querySelector('.utility-actions');if(utilityActions&&!utilityActions.querySelector('.instagram-link'))utilityActions.appendChild(makeInstagram('instagram-link','Instagram'));
const mobilePanelSocial=document.querySelector('.mobile-panel');if(mobilePanelSocial&&!mobilePanelSocial.querySelector('.mobile-instagram')){const quote=mobilePanelSocial.querySelector('.mobile-quote');const link=makeInstagram('mobile-instagram','Instagram ↗');quote?mobilePanelSocial.insertBefore(link,quote):mobilePanelSocial.appendChild(link)}
const footerContact=document.querySelector('.footer>div:nth-of-type(3)');if(footerContact&&!footerContact.querySelector('.footer-instagram'))footerContact.appendChild(makeInstagram('footer-instagram','Instagram @boxes_tasmaarah_collection'));
const motionQuery=matchMedia('(prefers-reduced-motion: reduce)');document.querySelectorAll('.motion-toggle').forEach(el=>el.remove());const applyMotion=()=>document.body.dataset.motion=motionQuery.matches?'off':'on';applyMotion();motionQuery.addEventListener?.('change',applyMotion);
const menu=document.querySelector('.mobile-menu');if(menu){const summary=menu.querySelector('summary'),panel=menu.querySelector('.mobile-panel'),header=document.querySelector('.site-header');if(panel&&!panel.id)panel.id='mobile-navigation-panel';if(summary&&panel)summary.setAttribute('aria-controls',panel.id);const positionPanel=()=>{if(!panel||!header)return;const top=Math.max(0,Math.round(header.getBoundingClientRect().bottom));root.style.setProperty('--mobile-menu-top',`${top}px`)};const sync=open=>{summary?.setAttribute('aria-expanded',String(open));summary?.setAttribute('aria-label',open?'Close navigation':'Open navigation');document.body.classList.toggle('menu-open',open);document.body.style.overflow=open?'hidden':'';if(open){positionPanel();requestAnimationFrame(()=>panel?.querySelector('a')?.focus({preventScroll:true}))}};const setOpen=open=>{menu.open=!!open;sync(!!open)};summary?.addEventListener('click',e=>{if(innerWidth<=980)e.preventDefault()});summary?.addEventListener('pointerup',e=>{if(innerWidth>980)return;e.preventDefault();e.stopPropagation();setOpen(!menu.open)});summary?.addEventListener('keydown',e=>{if(innerWidth>980)return;if(e.key==='Enter'||e.key===' '){e.preventDefault();setOpen(!menu.open)}});menu.addEventListener('toggle',()=>sync(menu.open));panel?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>setOpen(false)));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu.open){setOpen(false);summary?.focus()}else if(menu.open)trapTab(e,panel)});document.addEventListener('pointerdown',e=>{if(menu.open&&!menu.contains(e.target))setOpen(false)},{passive:true});addEventListener('resize',()=>{if(innerWidth>980&&menu.open)setOpen(false);else if(menu.open)positionPanel()},{passive:true});addEventListener('orientationchange',()=>setTimeout(()=>menu.open&&positionPanel(),160),{passive:true});sync(menu.open)}
const resetTransientUI=()=>{if(menu?.open){menu.open=false}document.body.classList.remove('menu-open','lightbox-open');document.body.style.overflow=''};addEventListener('pageshow',resetTransientUI);
const current=(location.pathname.split('/').pop()||'index.html').toLowerCase();document.querySelectorAll('.desktop-nav a,.mobile-panel a').forEach(a=>{if((a.getAttribute('href')||'').split('#')[0].toLowerCase()===current)a.setAttribute('aria-current','page')});
const cards=[...document.querySelectorAll('.catalog-card')],search=document.querySelector('[data-catalog-search]'),empty=document.querySelector('.empty-state');if(cards.length&&search){const status=document.createElement('p');status.className='catalog-results-status';status.setAttribute('role','status');status.setAttribute('aria-live','polite');search.closest('.catalog-toolbar')?.insertAdjacentElement('afterend',status);const filter=()=>{const q=search.value.trim().toLowerCase();let count=0;cards.forEach(card=>{const hit=!q||card.textContent.toLowerCase().includes(q);card.hidden=!hit;if(hit)count++});empty?.classList.toggle('show',count===0);status.textContent=q?`${count} ${count===1?'result':'results'} for “${search.value.trim()}”`:`${count} collection options`};search.value=new URLSearchParams(location.search).get('q')||'';search.addEventListener('input',filter);search.addEventListener('keydown',e=>{if(e.key==='Escape'&&search.value){search.value='';filter();search.focus()}});filter()}
const form=document.querySelector('#quote-form');if(form){const params=new URLSearchParams(location.search),setField=(name,value)=>{if(!value)return;const field=form.elements.namedItem(name);if(!field)return;if(field instanceof HTMLSelectElement){const match=[...field.options].find(o=>o.value.toLowerCase()===value.toLowerCase()||o.text.toLowerCase()===value.toLowerCase());if(match)field.value=match.value}else field.value=value};['occasion','service','material','size','details'].forEach(name=>setField(name,params.get(name)));const val=n=>String(new FormData(form).get(n)||'').trim();form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const labels={name:'Name',occasion:'Occasion',service:'Service',material:'Material',size:'Size',details:'Details'};const lines=["Hi Tasmaarah Collection, I'd like a quote.",''];Object.entries(labels).forEach(([name,label])=>{const field=form.elements.namedItem(name);if(!field)return;const value=val(name);if(value)lines.push(`${label}: ${value}`)});location.href=`https://wa.me/27635409729?text=${encodeURIComponent(lines.join('\n'))}`})}
const galleryImages=[...document.querySelectorAll('.masonry-gallery img')];if(galleryImages.length){const lightbox=document.createElement('div');lightbox.className='lightbox';lightbox.setAttribute('role','dialog');lightbox.setAttribute('aria-modal','true');lightbox.setAttribute('aria-label','Gallery viewer');lightbox.innerHTML='<button class="lightbox-close" type="button" aria-label="Close gallery">×</button><button class="lightbox-prev" type="button" aria-label="Previous image">‹</button><figure><img alt=""><figcaption></figcaption></figure><button class="lightbox-next" type="button" aria-label="Next image">›</button><a class="lightbox-enquire" target="_blank" rel="noopener">Ask about this look</a>';document.body.appendChild(lightbox);const image=lightbox.querySelector('img'),caption=lightbox.querySelector('figcaption'),closeButton=lightbox.querySelector('.lightbox-close'),enquire=lightbox.querySelector('.lightbox-enquire');let index=0,lastFocus=null,touchX=0;const show=n=>{index=(n+galleryImages.length)%galleryImages.length;image.src=galleryImages[index].currentSrc||galleryImages[index].src;image.alt=galleryImages[index].alt||'Tasmaarah presentation';caption.textContent=image.alt;enquire.href=`https://wa.me/27635409729?text=${encodeURIComponent(`Hi Tasmaarah Collection, I like this gallery presentation: ${image.alt}. Please tell me more about creating something similar.`)}`};const open=n=>{lastFocus=document.activeElement;show(n);lightbox.classList.add('open');document.body.classList.add('lightbox-open');document.body.style.overflow='hidden';closeButton?.focus()};const close=()=>{lightbox.classList.remove('open');document.body.classList.remove('lightbox-open');document.body.style.overflow='';lastFocus?.focus?.()};galleryImages.forEach((img,n)=>{img.tabIndex=0;img.setAttribute('role','button');img.setAttribute('aria-label',`Open image: ${img.alt||'Tasmaarah presentation'}`);img.addEventListener('click',()=>open(n));img.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open(n)}})});closeButton?.addEventListener('click',close);lightbox.querySelector('.lightbox-prev')?.addEventListener('click',()=>show(index-1));lightbox.querySelector('.lightbox-next')?.addEventListener('click',()=>show(index+1));lightbox.addEventListener('click',e=>{if(e.target===lightbox)close()});lightbox.addEventListener('touchstart',e=>{touchX=e.touches[0]?.clientX||0},{passive:true});lightbox.addEventListener('touchend',e=>{const end=e.changedTouches[0]?.clientX||touchX;if(Math.abs(end-touchX)>48)show(index+(end<touchX?1:-1))},{passive:true});document.addEventListener('keydown',e=>{if(!lightbox.classList.contains('open'))return;if(e.key==='Escape')close();else if(e.key==='ArrowLeft')show(index-1);else if(e.key==='ArrowRight')show(index+1);else trapTab(e,lightbox)})}
const reveals=[...document.querySelectorAll('[data-reveal]')];if('IntersectionObserver'in window&&!motionQuery.matches){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('reveal-enter');observer.unobserve(entry.target)}}),{threshold:.08,rootMargin:'8% 0px'});reveals.forEach(el=>observer.observe(el))}
if(matchMedia('(pointer:fine)').matches){let raf=0;addEventListener('pointermove',e=>{if(document.body.dataset.motion!=='on')return;cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>{root.style.setProperty('--pointer-x',`${Math.max(0,Math.min(100,e.clientX/innerWidth*100))}%`);root.style.setProperty('--pointer-y',`${Math.max(0,Math.min(100,e.clientY/innerHeight*100))}%`)})},{passive:true})}
document.querySelectorAll('main img').forEach(img=>{if(!img.classList.contains('hero-art')){img.decoding='async';if(!img.hasAttribute('loading'))img.loading='lazy'}img.addEventListener('load',()=>img.classList.add('is-loaded'),{once:true})});document.body.classList.add('site-ready');
})();