(()=>{
'use strict';
const d=document,w=window,root=d.documentElement;root.classList.add('js');
const exp=d.querySelector('link[href^="site-experience.css"]');if(exp)exp.href='site-experience.css?v=9';
const addCss=(href,key)=>{if(d.querySelector(`[data-${key}]`))return;const l=d.createElement('link');l.rel='stylesheet';l.href=href;l.dataset[key]='';d.head.appendChild(l)};
if(matchMedia('(min-width:981px)').matches){const fn=()=>addCss('desktop-polish.css?v=2','desktopPolish');'requestIdleCallback'in w?w.requestIdleCallback(fn,{timeout:700}):setTimeout(fn,0)}
const instagram='https://www.instagram.com/boxes_tasmaarah_collection';
const whatsapp='https://wa.me/27635409729?text='+encodeURIComponent("Hi Tasmaarah Collection, I'd like a quote.");
const maps='https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent('Reservoir Hills, Durban, KwaZulu-Natal, South Africa')+'&travelmode=driving&dir_action=navigate';
const external=(href,cls,label,text)=>{const a=d.createElement('a');a.href=href;a.target='_blank';a.rel='noopener noreferrer';a.className=cls||'';a.setAttribute('aria-label',label||text||'Open link');if(text)a.textContent=text;return a};
const svg={instagram:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.4" cy="6.6" r="1" fill="currentColor" stroke="none"/></svg>',whatsapp:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20 11.5a8 8 0 0 1-11.8 7L4 20l1.5-4.1A8 8 0 1 1 20 11.5Z"/><path d="M8.7 8.2c.2-.4.4-.4.7-.4h.5c.2 0 .4 0 .5.4l.8 1.8c.1.3.1.5-.1.7l-.6.8c-.2.2-.2.4 0 .7.6 1.1 1.4 1.9 2.5 2.5.3.2.5.2.7 0l.9-1c.2-.2.4-.3.7-.2l1.7.8c.3.1.4.3.4.5 0 .4-.2 1.2-.8 1.7-.5.5-1.2.8-2 .8-.7 0-1.6-.2-2.7-.7-1.3-.6-2.4-1.4-3.4-2.4-1-1-1.8-2.1-2.4-3.4-.5-1.1-.7-2-.7-2.7 0-.7.2-1.3.5-1.7Z"/></svg>'};
const icon=(kind,href,label)=>{const a=external(href,`social-icon social-icon-${kind}`,label);a.innerHTML=svg[kind];return a};
const socials=()=>{const x=d.createElement('div');x.className='social-icons';x.append(icon('instagram',instagram,'Instagram'),icon('whatsapp',whatsapp,'WhatsApp'));return x};
const utility=d.querySelector('.utility-actions');if(utility&&!utility.querySelector('.instagram-link'))utility.append(external(instagram,'instagram-link','Instagram','Instagram'));
const panel=d.querySelector('.mobile-panel');if(panel&&!panel.querySelector('.mobile-instagram')){const a=external(instagram,'mobile-instagram','Instagram','Instagram ↗'),q=panel.querySelector('.mobile-quote');q?panel.insertBefore(a,q):panel.append(a)}
const footerContact=d.querySelector('.footer>div:nth-of-type(3)');if(footerContact&&!footerContact.querySelector('.footer-instagram')){footerContact.append(external(instagram,'footer-instagram','Instagram','Instagram @boxes_tasmaarah_collection'),socials())}
const socialCopy=d.querySelector('.social-showcase-copy');if(socialCopy&&!socialCopy.querySelector('.social-icons'))socialCopy.append(socials());
const footer=d.querySelector('.footer');if(footer&&!footer.querySelector('a[href="privacy.html"]')){const a=d.createElement('a');a.href='privacy.html';a.className='footer-privacy';a.textContent='Privacy & cookies';footer.querySelector('.credit')?.insertAdjacentElement('beforebegin',a)}
d.querySelectorAll('span,p,address,div').forEach(el=>{if(el.children.length)return;const t=(el.textContent||'').trim();if(!/^(Reservoir Hills(?:,\s*Durban)?|Based in Reservoir Hills(?:,\s*Durban)?)$/i.test(t))return;el.replaceWith(external(maps,'map-directions-link','Get directions to Reservoir Hills, Durban',t))});
try{if(localStorage.getItem('tasmaarahPrivacyNotice')!=='dismissed'&&!location.pathname.endsWith('privacy.html')){const n=d.createElement('aside');n.className='cookie-notice';n.setAttribute('role','region');n.setAttribute('aria-label','Privacy and cookies notice');n.innerHTML='<p><strong>Privacy & cookies</strong>This site does not currently use advertising or analytics cookies. Dismissing this notice stores only that preference. <a href="privacy.html">Learn more</a>.</p><button type="button">Got it</button>';n.querySelector('button').onclick=()=>{localStorage.setItem('tasmaarahPrivacyNotice','dismissed');n.remove()};d.body.append(n)}}catch{}
const reduced=matchMedia('(prefers-reduced-motion: reduce)');d.body.dataset.motion=reduced.matches?'off':'on';reduced.addEventListener?.('change',e=>d.body.dataset.motion=e.matches?'off':'on');d.querySelectorAll('.motion-toggle').forEach(x=>x.remove());
/* Mobile navigation: native details toggle, JS only synchronises state. */
const menu=d.querySelector('.mobile-menu');if(menu){const summary=menu.querySelector('summary'),nav=menu.querySelector('.mobile-panel'),header=d.querySelector('.site-header');if(nav&&!nav.id)nav.id='mobile-navigation-panel';summary?.setAttribute('aria-controls',nav?.id||'mobile-navigation-panel');const pos=()=>root.style.setProperty('--mobile-menu-top',`${Math.max(0,Math.round(header?.getBoundingClientRect().bottom||82))}px`);const sync=()=>{const open=menu.open;summary?.setAttribute('aria-expanded',String(open));summary?.setAttribute('aria-label',open?'Close navigation':'Open navigation');d.body.classList.toggle('menu-open',open);d.body.style.overflow=open?'hidden':'';if(open)pos()};menu.addEventListener('toggle',sync);nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.open=false;sync()}));d.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu.open){menu.open=false;sync();summary?.focus()}});d.addEventListener('pointerdown',e=>{if(menu.open&&!menu.contains(e.target)){menu.open=false;sync()}},{passive:true});w.addEventListener('resize',()=>{if(menu.open)pos()},{passive:true});sync()}
/* Keep the branded menu control within thumb reach after the visitor scrolls away from the top. */
let navRaf=0;const syncScrollNav=()=>{navRaf=0;const scrolled=w.innerWidth<=980&&w.scrollY>96;d.body.classList.toggle('nav-scrolled',scrolled)};const queueScrollNav=()=>{if(!navRaf)navRaf=w.requestAnimationFrame(syncScrollNav)};w.addEventListener('scroll',queueScrollNav,{passive:true});w.addEventListener('resize',queueScrollNav,{passive:true});syncScrollNav();
w.addEventListener('pageshow',()=>{if(menu)menu.open=false;d.body.classList.remove('menu-open','lightbox-open');d.body.style.overflow='';syncScrollNav()});
const current=(location.pathname.split('/').pop()||'index.html').toLowerCase();d.querySelectorAll('.desktop-nav a,.mobile-panel a').forEach(a=>{if((a.getAttribute('href')||'').split('#')[0].toLowerCase()===current)a.setAttribute('aria-current','page')});
const cards=[...d.querySelectorAll('.catalog-card')],search=d.querySelector('[data-catalog-search]'),empty=d.querySelector('.empty-state');if(cards.length&&search){const status=d.createElement('p');status.className='catalog-results-status';status.setAttribute('role','status');search.closest('.catalog-toolbar')?.insertAdjacentElement('afterend',status);const filter=()=>{const q=search.value.trim().toLowerCase();let n=0;cards.forEach(c=>{const hit=!q||c.textContent.toLowerCase().includes(q);c.hidden=!hit;if(hit)n++});empty?.classList.toggle('show',!n);status.textContent=q?`${n} ${n===1?'result':'results'} for “${search.value.trim()}”`:`${n} collection options`};search.value=new URLSearchParams(location.search).get('q')||'';search.addEventListener('input',filter);filter()}
const form=d.querySelector('#quote-form');if(form){const p=new URLSearchParams(location.search);['occasion','service','material','size','details'].forEach(name=>{const f=form.elements.namedItem(name),v=p.get(name);if(f&&v)f.value=v});form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const fd=new FormData(form),labels={name:'Name',occasion:'Occasion',service:'Service',material:'Material',size:'Size',details:'Details'},lines=["Hi Tasmaarah Collection, I'd like a quote.",''];Object.entries(labels).forEach(([k,l])=>{const v=String(fd.get(k)||'').trim();if(v)lines.push(`${l}: ${v}`)});location.href=`https://wa.me/27635409729?text=${encodeURIComponent(lines.join('\n'))}`})}
const imgs=[...d.querySelectorAll('.masonry-gallery img')];if(imgs.length){const lb=d.createElement('div');lb.className='lightbox';lb.setAttribute('role','dialog');lb.setAttribute('aria-modal','true');lb.innerHTML='<button class="lightbox-close" type="button" aria-label="Close">×</button><button class="lightbox-prev" type="button" aria-label="Previous">‹</button><figure><img alt=""><figcaption></figcaption></figure><button class="lightbox-next" type="button" aria-label="Next">›</button><a class="lightbox-enquire" target="_blank" rel="noopener noreferrer">Ask about this look</a>';d.body.append(lb);const image=lb.querySelector('img'),cap=lb.querySelector('figcaption'),ask=lb.querySelector('.lightbox-enquire');let i=0,last;const show=n=>{i=(n+imgs.length)%imgs.length;image.src=imgs[i].currentSrc||imgs[i].src;image.alt=imgs[i].alt||'Tasmaarah presentation';cap.textContent=image.alt;ask.href=`https://wa.me/27635409729?text=${encodeURIComponent(`Hi Tasmaarah Collection, I like this presentation: ${image.alt}. Please tell me more.`)}`};const open=n=>{last=d.activeElement;show(n);lb.classList.add('open');d.body.classList.add('lightbox-open');d.body.style.overflow='hidden'};const close=()=>{lb.classList.remove('open');d.body.classList.remove('lightbox-open');d.body.style.overflow='';last?.focus?.()};imgs.forEach((im,n)=>{im.tabIndex=0;im.setAttribute('role','button');im.onclick=()=>open(n);im.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open(n)}}});lb.querySelector('.lightbox-close').onclick=close;lb.querySelector('.lightbox-prev').onclick=()=>show(i-1);lb.querySelector('.lightbox-next').onclick=()=>show(i+1);lb.onclick=e=>{if(e.target===lb)close()};d.addEventListener('keydown',e=>{if(!lb.classList.contains('open'))return;if(e.key==='Escape')close();if(e.key==='ArrowLeft')show(i-1);if(e.key==='ArrowRight')show(i+1)})}
const reveals=[...d.querySelectorAll('[data-reveal]')];if('IntersectionObserver'in w&&!reduced.matches){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('reveal-enter');io.unobserve(e.target)}}),{threshold:.04,rootMargin:'18% 0px'});reveals.forEach(x=>io.observe(x))}else reveals.forEach(x=>x.classList.add('reveal-enter'));
d.querySelectorAll('main img').forEach(img=>{if(!img.classList.contains('hero-art')){img.decoding='async';if(!img.hasAttribute('loading'))img.loading='lazy'}});d.body.classList.add('site-ready');
})();